services:
  app:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    restart: unless-stopped
